spring:
  profiles:
    active: local # 运行模式

  application:
    name: ${system.micro-name} # 服务注册时的名称

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  data:
    mongodb:
      uri: ${system.mongo.uri}