spring:
  datasource:
    hikari:
      username: root
      password: 123123
    #url: jdbc:mysql://192.168.44.200:3306/school?useSSL=false&characterEncoding=utf-8
    url: jdbc:mysql://192.168.2.185:3333/school?useSSL=false&characterEncoding=utf-8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印实际执行的SQL
    map-underscore-to-camel-case: true # 将sql查出来带下划线的字段在bean对象里转成驼峰命名
  type-enums-package: me.beagle4ce.training.*.model.enums # 为了使通用枚举生效，需要指定好枚举所在地址
  global-config:
    db-config:
      logic-delete-field: valid # 用于标记逻辑删除的字段
      logic-not-delete-value: 1 # 未删除时的值
      logic-delete-value: 0  # 删除时的值

param:
  test: 101,102,103
