spring:
  profiles:
    active: local # 运行模式

  application:
    name: ${system.micro-name} # 服务注册时的名称

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: ${system.mysql.url}
    username: root
    password: ${system.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver # hikari连接池使用新的jdbc Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialSize: 5  # 指定启动连接池时，初始建立的连接数量
    hikari:
      connection-timeout: 3000
      idle-timeout: 30000
      minimum-idle: 2
      maximum-pool-size: 2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL57Dialect
    database: mysql
    open-in-view: false # 关闭repository直接投射到controller层
    properties:
      hibernate.max_fetch_depth: 0
      hibernate.format_sql: true